# Generated by Django 5.1.1 on 2024-11-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Вопрос',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Автор ответа',
            new_name='responder',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Автор вопроса',
            new_name='author',
        ),
    ]
