# Generated by Django 5.1.1 on 2024-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_вопрос_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='Текст ответа',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Текст вопроса',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default='default', verbose_name='Текст ответа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='default', verbose_name='Текст вопроса'),
            preserve_default=False,
        ),
    ]
