# Generated by Django 5.1.1 on 2024-11-23 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя исполнителя', models.CharField(db_index=True, max_length=60, unique=True)),
                ('Биография исполнителя', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название жанра', models.CharField(db_index=True, max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название альбома', models.CharField(db_index=True, max_length=60)),
                ('Описание альбома', models.CharField(max_length=1024)),
                ('Обложка альбома', models.ImageField(upload_to='album_covers/')),
                ('Исполнитель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='content.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название трека', models.CharField(db_index=True, max_length=60)),
                ('Текст трека', models.CharField(blank=True, max_length=1024)),
                ('Описание трека', models.CharField(blank=True, max_length=1024)),
                ('Обложка трека', models.ImageField(upload_to='song_covers/')),
                ('Альбомы', models.ManyToManyField(blank=True, related_name='songs', to='content.album')),
                ('Жанр', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='content.genre')),
                ('Исполнитель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='content.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название плейлиста', models.CharField(db_index=True, max_length=60)),
                ('Обложка плейлиста', models.ImageField(upload_to='playlist_covers/')),
                ('Пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('Треки', models.ManyToManyField(related_name='playlists', to='content.song')),
            ],
        ),
    ]
