# Generated by Django 5.1.1 on 2024-11-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='Название жанра',
            new_name='name',
        ),
    ]
