# Generated by Django 5.1.1 on 2024-11-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_название_жанра_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Биография исполнителя',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='Имя исполнителя',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Альбомы',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Исполнитель',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Обложка трека',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Описание трека',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Жанр',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Название трека',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Текст трека',
            new_name='text',
        ),
    ]
