# Generated by Django 5.1.1 on 2024-11-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_cover_song_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Исполнитель',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Описание альбома',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Обложка альбома',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Название альбома',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='Обложка плейлиста',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='Треки',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='Название плейлиста',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='Пользователь',
            new_name='user',
        ),
    ]
