# Generated by Django 5.1.1 on 2024-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_song_track_alter_playlist_picture_alter_song_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
