# Generated by Django 5.1.1 on 2024-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_song_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(default='defaults/artist_default.png', upload_to='artist_covers/'),
        ),
    ]
