# Generated by Django 5.1.1 on 2024-11-29 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_artist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])]),
        ),
    ]
