# Generated by Django 5.1.1 on 2024-12-02 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_song_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='picture',
            field=models.ImageField(blank=True, default='defaults/song_default.png', upload_to='song_covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(default='defaults/song_track_default.mp3', upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4'])]),
        ),
    ]
