# Generated by Django 5.1.1 on 2024-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_song_picture_alter_song_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='picture',
            field=models.ImageField(blank=True, default='defaults/playlist_default.png', upload_to='playlist_covers/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='content.song'),
        ),
    ]
