# Generated by Django 5.1.1 on 2024-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('moderator', 'MODERATOR'), ('common', 'COMMON')], default='common', max_length=20),
        ),
    ]
